# Generated by Django 5.1.1 on 2024-09-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='guest_list',
            field=models.JSONField(default=list),
        ),
    ]
