# Generated by Django 5.1.1 on 2024-09-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_amenities_amenitiesavailed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='guest_list',
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=100)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transaction')),
            ],
        ),
    ]
