# Generated by Django 5.1.1 on 2024-09-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_gueststatus_remove_transaction_guest_list_guestlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlist',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.gueststatus'),
        ),
    ]
