# Generated by Django 5.1.1 on 2024-09-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_guestlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.gueststatus'),
        ),
    ]
