# Generated by Django 5.1.1 on 2024-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_activity_paymentmethod_activitiesavailed_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesavailed',
            name='hours_availed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
