# Generated by Django 5.0.7 on 2024-09-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_transaction_booking_customer_bill'),
        ('transactions', '0011_paymentstatus_payment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Billing',
        ),
        migrations.RenameField(
            model_name='activitiesavailed',
            old_name='transaction',
            new_name='customer_bill',
        ),
        migrations.RenameField(
            model_name='amenitiesavailed',
            old_name='transaction',
            new_name='customer_bill',
        ),
        migrations.RenameField(
            model_name='foodbill',
            old_name='transaction',
            new_name='customer_bill',
        ),
        migrations.RenameField(
            model_name='guestlist',
            old_name='transaction',
            new_name='customer_bill',
        ),
        migrations.RenameField(
            model_name='payment',   
            old_name='transaction',
            new_name='customer_bill',
        ),
    ]
