# Generated by Django 5.0.7 on 2024-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_rename_transaction_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
