# Generated by Django 5.0.7 on 2024-09-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_amenities_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='time',
        ),
    ]
