# Generated by Django 5.0.7 on 2024-10-05 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_alter_activitiesavailed_customer_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditonalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_payment', to='transactions.billing')),
            ],
        ),
    ]
