# Generated by Django 5.0.7 on 2024-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_additonalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbill',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodbill',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
