# Generated by Django 5.0.7 on 2024-09-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='good_for',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
