# Generated by Django 5.0.7 on 2024-09-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_roomtype_good_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='max_guests',
            new_name='max_adult',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='max_children',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
