# Generated by Django 5.0.7 on 2024-09-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_max_guests_roomtype_max_adult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='transaction',
            new_name='customer_bill',
        ),
    ]
