# Generated by Django 5.0.7 on 2024-10-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_booking_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="number_of_guests",
            new_name="adult_count",
        ),
        migrations.AddField(
            model_name="booking",
            name="children_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
