# Generated by Django 5.0.7 on 2024-10-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_rename_number_of_guests_booking_adult_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room",
                to="bookings.roomstatus",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room",
                to="bookings.roomtype",
            ),
        ),
    ]
