POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{"username":"admin", "password":"123"}

###

POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{"username":"bobby", "password":"123", "email":"email@gmail.com"}

###

GET http://127.0.0.1:8000/api/test_token
Content-Type: application/json
Authorization: Token c2292d8a2308fcb379366666bf603e66e8308110

{}

###

GET http://127.0.0.1:8000/api/tt2
Content-Type: application/json
Authorization: Token c2292d8a2308fcb379366666bf603e66e8308110

{}